services:
  - type: web
    name: phishguard
    runtime: docker
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PHISHGUARD_API_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false # User must provide this secret (connection string) in Dashboard
      - key: APP_NAME
        value: PhishGuard
      - key: DEBUG
        value: "false"
